### ISSUE TITLE
Share your IntelliJ color scheme on http://ideacolorschemes.com

### ISSUE THREAD

**Issue by iron9light** [sirthias/BlueForest#19]
I'm the founder of http://ideacolorschemes.com

It's a website and [plugin](http://plugins.intellij.net/plugin/?idea&id=6892) to share IntelliJ color schemes.

It will be awesome if you can upload and share yours.

Best regards,

IL

**Comment by analytically** [comment]
This is a spam domain now.

**Comment by sirthias** [comment]
Ok, thanks, Mathias!

**Comment by wqtty** [comment]
@iron9light  I believe that the domain name has got some problem.

**Comment by ferenczy** [comment]
@iron9light There's nothing on that domain.
