### ISSUE TITLE
Install on Version 14?

### ISSUE THREAD

**Issue by alexanderhblack** [sirthias/BlueForest#39]
Doesn't seem to be a colors folder anymore on the OS X version, so not sure how to install it. Any help would be appreciated!

**Comment by sirthias** [comment]
Just checked,  on my machine this is where things live:

```
> find . | g BlueForest
./Preferences/IntelliJIdea13/colors/BlueForest.icls
./Preferences/IntelliJIdea14/colors/BlueForest.icls
```

And I do run BlueForest on IDEA 14 without any issues.

**Comment by alexanderhblack** [comment]
Good to know, thank you!
