### ISSUE TITLE
Changes needed for IntelliJ IDEA 2016.1

### ISSUE THREAD

**Issue by Sciss** [sirthias/BlueForest#47]
I just gave the new IntelliJ version a shot. Seems they introduced some changes, I'm seeing a lot of black text should should have a bright colour.

**Comment by sirthias** [comment]
Ok, thanks. I'll look into it as soon as I've upgraded myself.

**Comment by emstlk** [comment]
@Sciss Got the same problem, but actually it was my mistake by changes in my local repo
Everything is ok after `git reset --hard` and redeploy

**Comment by Sciss** [comment]
@emstlk Alright, yeah sorry my bad. This helped!
