### ISSUE TITLE
Spam Domain

### ISSUE THREAD

**Issue by brendan-benting** [sirthias/BlueForest#49]
This domain is now spam. Please remove links.

**Comment by sirthias** [comment]
Brendan,
which domain/link do you mean exactly?

**Comment by brendan-benting** [comment]
Not here, but the listing on the jetbrains plugin directory links to the
spam site.

**Comment by sirthias** [comment]
Could you supply a link to the page where the bad link is?

**Comment by brendan-benting** [comment]
I think I confused this repo with the original site meant to host different
editor themes. Sorry and please excuse this issue :)

**Comment by sirthias** [comment]
No problem at all.
